###
POST http://localhost:8080/order
Content-Type: application/json

{
  "customerName": "Kacper1",
  "delivery": {
    "courierName": "Bartek1",
    "status": "CREATED"
  },
  "items": [{
    "quantity": 5,
    "product": {
      "name": "pizza1",
      "price": 500
    }},
    {
    "quantity": 10,
    "product": {
      "name": "pizza1",
      "price": 500
    }
  }]
}

###
PATCH http://localhost:8080/order/1
Content-Type: application/json

{
  "status": "DELIVERED"
}

###
GET http://localhost:8090/order-history?page=0&size=3
Accept: application/json



